basic_app/urls.py
from django.urls import path, re_path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    re_path(r'^$', views.SchoolListView.as_view(), name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.SchoolDeleteView.as_view(), name='delete')
]

cbv_project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('basic_app/', include('basic_app.urls', namespace='basic_app'))
]

basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

basic_app/views.py
from django.shortcuts import render
from django.views.generic import (
    View, TemplateView, ListView,
    DetailView, CreateView,
    UpdateView, DeleteView)
from django.urls import reverse_lazy
from . import models


# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['injectme'] = 'BASIC INJECTION'
    #     return context


class SchoolListView(ListView):

    """
    name of the context by default is 'school_list';
    changed to 'schools'
    """

    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):

    """
    name of the context by default is 'school';
    changed to 'school_details'
    """
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
{# Load the tag library #}
{% load bootstrap4 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BASE</title>
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
            aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarToggler">
        <a class="navbar-brand" href="#">DJANGO APP</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'basic_app:list' %}">Schools</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">-</a>
            </li>
        </ul>
    </div>
</nav>

<div class="container">
    {% block body_block %}

    {% endblock %}
</div>

</body>
</html>

basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{# Load the tag library #}
{% load bootstrap4 %}

{% block body_block %}
    <p class="lead">
        Are you sure you want to delete "{{ school.name }}" ?
    </p>

    <form method="post" class="form-group">
        {% csrf_token %}
        {% buttons %}
            <button type="submit" class="btn btn-danger" value="Delete">Confirm Delete</button>
            <a class="btn btn-primary" href="{% url 'basic_app:detail' pk=school.pk %}" >Cancel</a>
        {% endbuttons %}
    </form>

{% endblock %}

basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}
{# Load the tag library #}
{% load bootstrap4 %}

{% block body_block %}
    <div>
        <h2 class="display-4">School Details:</h2>

        <p>Name: {{ school_detail.name }}</p>
        <p>Principal: {{ school_detail.principal }}</p>
        <p>Location: {{ school_detail.location }}</p>
    </div>

    <div>
        <h3>Students: </h3>

        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">NAME</th>
                <th scope="col">AGE</th>
            </tr>
            </thead>
            <tbody>
            {% for student in school_details.students.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ student.name }}</td>
                    <td>{{ student.age }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}" role="button">Update</a>
    <a class="btn btn-danger" href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a>

{% endblock %}

basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}
{# Load the tag library #}
{% load bootstrap4 %}

{% block body_block %}

    <h2>
        {% if not from.instance.pk %}
            Create School
        {% else %}
            Update School
        {% endif %}
    </h2>


    {# Display a form #}
    <form method="post" class="form-group">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary" value="Submit">Submit</button>
        {% endbuttons %}
    </form>



{% endblock %}

basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}


    <h2 class="display-4">List of schools: </h2>

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">NAME</th>
        </tr>
        </thead>
        <tbody>
        {% for school in schools %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>
                    <a href="{{ school.id }}">{{ school.name }}</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/basic.html
<!DOCTYPE html>
{# Load the tag library #}
{% load bootstrap4 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
            aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarToggler">
        <a class="navbar-brand" href="#">DJANGO APP</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'basic_app:list' %}">Schools</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">-</a>
            </li>
        </ul>
    </div>
</nav>

<div class="container">
    {% block body_block %}

    {% endblock %}
</div>

</body>
</html>

templates/index.html
{% extends "basic.html" %}
    {% block body_block %}

        <div class="jumbotron">
            <h1 class="display-4">Homepage</h1>
        </div>

    {% endblock %}